version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"       
      - "8883:8883"       
      - "8083:8083"       
      - "8084:8084"       
      - "18083:18083"     
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public
      - EMQX_MAX_CLIENTS=1000
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_NODE__NAME=emqx@127.0.0.1
      - EMQX_NODE__COOKIE=emqxsecretcookie
      - EMQX_NODE__DATA_DIR=/opt/emqx/data
    volumes:
      - ./cert:/opt/emqx/etc/certs
      - ./emqx.conf:/opt/emqx/etc/emqx.conf
