version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx_conf
    restart: unless-stopped
    ports:
      - "1883:1883"       
      - "8883:8883"       
      - "8083:8083"       
      - "8084:8084"       
      - "18083:18083"     
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public
      - EMQX_MAX_CLIENTS=1000
      - EMQX_ALLOW_ANONYMOUS=true